### ISSUE TITLE
Trying to add new attributes to passive mobs throws an internal error

### ISSUE THREAD

**Issue by GoldenShad0w** [GamerCoder215/MobChip#46]
### Bug Type

Console Errors

### Description

When trying to add the generic attack damage attribute to a passive mob with the code described on the wiki, an error gets thrown and the attribute isn't applied.

```
EntityBrain brain = BukkitBrain.getBrain((Mob) entity);

AttributeInstance attack = brain.getAttributeInstance(EntityAttribute.GENERIC_ATTACK_DAMAGE);
attack.setBaseValue(2.0D);
AttributeInstance knockback = brain.getAttributeInstance(EntityAttribute.GENERIC_ATTACK_KNOCKBACK);
knockback.setBaseValue(1.0D);
```

Btw there are also two syntax errors on the wiki:

`getAttribteInstance` is misspelt and `attack.addModifier(new AttributeModifier(UUID.randomUUID(), "modifier-1", 5.0D, AttributeModifier.Operation.MULTIPLY_SCALAR_1);` doesn't close all brackets.

### Expected Behavior

The attribute should be applied and visible with `/data get entity <uuid>`

### Actual Behavior

Console throws following error:

```
[15:56:01 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'aurum' in plugin Aurum v1.0-SNAPSHOT
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-362]
    at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-362]
    at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
    at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
    at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
    at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-362]
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-362]
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-362]
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-362]
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-362]
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-362]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-362]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-362]
    at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "this.handle" is null
    at me.gamercoder215.mobchip.abstraction.v1_19_R2.AttributeInstance1_19_R2.setBaseValue(AttributeInstance1_19_R2.java:37) ~[aurum-1.0-SNAPSHOT.jar:?]
    at goldenshadow.aurum.Commands.onCommand(Commands.java:1531) ~[aurum-1.0-SNAPSHOT.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
    ... 23 more
```

**Comment by GamerCoder215** [comment]
Can confirm this happens. Will work on a fix for v1.8.1.

**Comment by GamerCoder215** [comment]
[`54f7d99`](https://github.com/GamerCoder215/MobChip/commit/54f7d993e52cc3c58f42a285c4986e873f510961) has been tested and works. 

Marking as completed. Will be officially released along with v1.8.1, but you can manually clone the branch and build the JAR yourself if you want.

**Comment by GoldenShad0w** [comment]
@GamerCoder215 I've cloned your repository and checked out to the 1.18.1 branch but im unsure which maven build i need to run. Is it this one? 
<img width="470" alt="Screenshot 2023-03-05 at 19 07 19" src="https://user-images.githubusercontent.com/115712806/222978030-eb4a440d-3039-49e5-95cc-aebeb4b8814c.png">

**Comment by GamerCoder215** [comment]
It should be `package`, the regular JAR built in the `bukkit/target` folder (not sources or javadoc) should be the one you use.

**Comment by GoldenShad0w** [comment]
@GamerCoder215 which one should i do? sorry if im annoying you
<img width="480" alt="Screenshot 2023-03-05 at 19 52 36" src="https://user-images.githubusercontent.com/115712806/222980073-c3eea63d-e731-4ace-951f-93e3ee227f64.png">

**Comment by GamerCoder215** [comment]
It's fine;

The parent one will run all of them, which is necessary to build the jar you need.

**Comment by GoldenShad0w** [comment]
@GamerCoder215 Ok I've done that but im getting a ClassNotFound exception when trying to create a EntityBrain like this `EntityBrain brain = BukkitBrain.getBrain((Mob) entity);` 

`[20:50:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'aurum' in plugin Aurum v1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912) ~[paper-1.19.3.jar:git-Paper-425]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-425]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-425]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-425]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-425]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-425]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-425]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-425]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-425]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-425]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: me/gamercoder215/mobchip/bukkit/BukkitBrain
	at goldenshadow.aurum.entities.CustomEntity.deserialize(CustomEntity.java:54) ~[aurum-1.0-SNAPSHOT.jar:?]
	at goldenshadow.aurum.Commands.onCommand(Commands.java:1669) ~[aurum-1.0-SNAPSHOT.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more
Caused by: java.lang.ClassNotFoundException: me.gamercoder215.mobchip.bukkit.BukkitBrain
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:181) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:148) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at goldenshadow.aurum.entities.CustomEntity.deserialize(CustomEntity.java:54) ~[aurum-1.0-SNAPSHOT.jar:?]
	at goldenshadow.aurum.Commands.onCommand(Commands.java:1669) ~[aurum-1.0-SNAPSHOT.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more`




Am I maybe doing something wrong in my pom.xml?

<img width="678" alt="Screenshot 2023-03-05 at 20 53 20" src="https://user-images.githubusercontent.com/115712806/222982671-639272a8-5495-4dd6-ad9c-c91997565488.png">

**Comment by GamerCoder215** [comment]
Your plugin isn't shading that JAR into the plugin jar.

Try changing your scope to `compile`.

**Comment by GoldenShad0w** [comment]
@GamerCoder215  Ok ive done that but now it gives me the following error when trying to compile the plugin and if i remove <systemPath> then how will it know where to get the jar from?
<img width="853" alt="Screenshot 2023-03-05 at 21 15 05" src="https://user-images.githubusercontent.com/115712806/222983627-b4599439-0ce5-459a-88af-1d3f9d8505ee.png">

**Comment by GoldenShad0w** [comment]
nvm i figured it out, ty for being so patient with me :)

**Comment by GamerCoder215** [comment]
I've just looked at it, and it seems like the `system` scope is deprecated, and it isn't possible to shade that JAR into your plugin jar.

I've created a [wiki page](https://github.com/GamerCoder215/MobChip/wiki/Using-an-Experimental-Version-of-MobChip) that is an alternative to that method.
