### ISSUE TITLE
Adding PathfinderMeleeAttack to certain entities causes an internal error

### ISSUE THREAD

**Issue by GoldenShad0w** [GamerCoder215/MobChip#53]
### Bug Type

Console Errors

### MobChip Version

1.8.1

### Server Version

Paper 1.19.3

### Description

Trying to add a PathfinderMeleeAttack to certain mobs throws a NoSuchMethodError exception. I have tried both `target.put(new PathfinderMeleeAttack((Creature) entity),0);` and`goal.put(new PathfinderMeleeAttack((Creature) entity),0);`. A mob to test this on is Panda, but I have encountered the same issue with mobs like wolfs, striders and llamas.

### Expected Behavior

Pathfinder should be added.

### Actual Behavior

```
[01:14:04 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'aurum' in plugin Aurum v1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.3.jar:git-Paper-442]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-442]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-442]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-442]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-442]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-442]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-442]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-442]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-442]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-442]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.EnumSet net.minecraft.world.entity.ai.goal.PathfinderGoal.j()'
	at me.gamercoder215.mobchip.abstraction.v1_19_R2.ChipUtil1_19_R2$3.getFlags(ChipUtil1_19_R2.java:1269) ~[aurum-1.0-SNAPSHOT.jar:?]
	at me.gamercoder215.mobchip.abstraction.v1_19_R2.ChipUtil1_19_R2.custom(ChipUtil1_19_R2.java:1256) ~[aurum-1.0-SNAPSHOT.jar:?]
	at me.gamercoder215.mobchip.abstraction.v1_19_R2.ChipUtil1_19_R2.toNMS(ChipUtil1_19_R2.java:505) ~[aurum-1.0-SNAPSHOT.jar:?]
	at me.gamercoder215.mobchip.abstraction.v1_19_R2.ChipUtil1_19_R2.addPathfinder(ChipUtil1_19_R2.java:517) ~[aurum-1.0-SNAPSHOT.jar:?]
	at me.gamercoder215.mobchip.abstraction.ChipUtil.addPathfinders(ChipUtil.java:58) ~[aurum-1.0-SNAPSHOT.jar:?]
	at me.gamercoder215.mobchip.bukkit.BukkitAI.updateAI(BukkitAI.java:43) ~[aurum-1.0-SNAPSHOT.jar:?]
	at me.gamercoder215.mobchip.bukkit.BukkitAI.add(BukkitAI.java:118) ~[aurum-1.0-SNAPSHOT.jar:?]
	at me.gamercoder215.mobchip.bukkit.BukkitAI.put(BukkitAI.java:75) ~[aurum-1.0-SNAPSHOT.jar:?]
	at goldenshadow.aurum.entities.CustomEntity.deserialize(CustomEntity.java:231) ~[aurum-1.0-SNAPSHOT.jar:?]
	at goldenshadow.aurum.Commands.onCommand(Commands.java:2086) ~[aurum-1.0-SNAPSHOT.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by GamerCoder215** [comment]
This IS a bug within the Paper Jar;

The method to retrieve the PathfinderGoal Flags was changed in the abstract PathfinderGoal class in Paper and Paper Forks, but not in Spigot.

I would talk to the Paper Devs, or switch your server JAR to Spigot or a non-paper Spigot Fork.
