### ISSUE TITLE
Broken codemc & jitpack release

### ISSUE THREAD

**Issue by Blaackyy** [GamerCoder215/MobChip#69]
### Bug Type

Other Unexpected Behavior

### MobChip Version

1.9.0

### Server Version

PaperMC 1.19.4 and PurpurMC 1.19.4, both latest.

### Description

Using gradle and Intellij.

Seems like the 1.9.0 release at codemc is broken, either by the IDE behavior (just limited to download the pom files) or by a visual check. I had no problem implementing v1.8.1.

Opted out to locally import the lib, due to that it seems like the 1.9.0 version is not reobfucated:
```java [20:32:58] [Server thread/INFO]: Blackyyy_ issued server command: /test
[20:32:58] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'test' in dev.blacky.testplugin.SimpleCommand(test)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:921) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2389) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2349) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/entity/LivingEntity
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at dev.blacky.testplugin.lib.mobchip.abstraction.ChipUtil.getWrapper(ChipUtil.java:188) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at dev.blacky.testplugin.lib.mobchip.bukkit.BukkitBrain.<clinit>(BukkitBrain.java:43) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at dev.blacky.testplugin.SimpleCommand.execute(SimpleCommand.java:26) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 22 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.entity.LivingEntity
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at dev.blacky.testplugin.lib.mobchip.abstraction.ChipUtil.getWrapper(ChipUtil.java:188) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at dev.blacky.testplugin.lib.mobchip.bukkit.BukkitBrain.<clinit>(BukkitBrain.java:43) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at dev.blacky.testplugin.SimpleCommand.execute(SimpleCommand.java:26) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 22 more
```
	
Thought it was because i was applying stuff right after spawning the entity but still:
```java 
[20:44:40] [Server thread/WARN]: [TestPlugin] Task #6 for TestPlugin v1.0.0 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/world/entity/LivingEntity
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at dev.blacky.testplugin.lib.mobchip.abstraction.ChipUtil.getWrapper(ChipUtil.java:188) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at dev.blacky.testplugin.lib.mobchip.bukkit.BukkitBrain.<clinit>(BukkitBrain.java:43) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at dev.blacky.testplugin.SimpleCommand.lambda$execute$0(SimpleCommand.java:29) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.entity.LivingEntity
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
```

Then after just using a basic call to test it wasn't me:

````java 
[20:45:55] [Server thread/INFO]: Blackyyy_ issued server command: /test
[20:45:56] [Server thread/WARN]: [TestPlugin] Task #2 for TestPlugin v1.0.0 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/core/Vec3i
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at dev.blacky.testplugin.lib.mobchip.abstraction.ChipUtil.getWrapper(ChipUtil.java:188) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at dev.blacky.testplugin.lib.mobchip.bukkit.BukkitBrain.<clinit>(BukkitBrain.java:43) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at dev.blacky.testplugin.SimpleCommand.lambda$execute$0(SimpleCommand.java:29) ~[TestPlugin.jar-1.0.0-all.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-538]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.core.Vec3i
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
```



### Expected Behavior

Be able to import and use v1.9.0 from codemc or jitpack repo.

### Actual Behavior

The library at codemc seems to be broken at v1.9.0, can't import from the repos (codemc and jitpack) but I can import and use an older version.

**Comment by GamerCoder215** [comment]
Fixed in #68. The CodeMC Jenkins canceled the original commit due to overloading time errors, so it should be able to redownload shortly.
