### ISSUE TITLE
Can't clear pathfinders from some mobs on Paper 1.16.5

### ISSUE THREAD

**Issue by datatags** [GamerCoder215/MobChip#75]
### Bug Type

Compatibility Issues, Console Errors

### MobChip Version

1.9.0

### Server Version

Paper 1.16.5

### Description

Clearing pathfinders from some mobs on Paper 1.16.5 produces an error. This only affects Paper 1.16.5, it does not affect Spigot as far as I can tell.

Despite the same actions on the same version triggering the issue, it does NOT appear to be related to #74, so I have opened a new issue for it.

### Expected Behavior

Pathfinders should be cleared

### Actual Behavior

An exception is thrown: (Root exception is just a CommandException so I have omitted it)
```
Caused by: java.lang.AssertionError: Could not find flags
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_16_R3.ChipUtil1_16_R3.getFlags(ChipUtil1_16_R3.java:1149) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_16_R3.ChipUtil1_16_R3$3.getFlags(ChipUtil1_16_R3.java:1164) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_16_R3.ChipUtil1_16_R3.custom(ChipUtil1_16_R3.java:1206) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_16_R3.ChipUtil1_16_R3.toNMS(ChipUtil1_16_R3.java:365) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_16_R3.ChipUtil1_16_R3.removePathfinder(ChipUtil1_16_R3.java:389) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.ChipUtil.lambda$clearPathfinders$0(ChipUtil.java:54) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_372]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.ChipUtil.clearPathfinders(ChipUtil.java:54) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitAI.updateAI(BukkitAI.java:42) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitAI.clear(BukkitAI.java:164) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.clearPathfinders(Pet.java:138) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.initializeEntity(Pet.java:122) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.onEquip(Pet.java:87) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:105) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:157) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:66) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:31) ~[?:?]
        at be.isach.ultracosmetics.command.subcommands.SubCommandToggle.toggle(SubCommandToggle.java:92) ~[?:?]
        at be.isach.ultracosmetics.command.subcommands.SubCommandToggle.onExePlayer(SubCommandToggle.java:48) ~[?:?]
        at be.isach.ultracosmetics.command.CommandManager.onCommand(CommandManager.java:81) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-794]
        ... 19 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R3.PathfinderGoal.i()
        at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_372]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_16_R3.ChipUtil1_16_R3.getFlags(ChipUtil1_16_R3.java:1145) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_16_R3.ChipUtil1_16_R3$3.getFlags(ChipUtil1_16_R3.java:1164) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_16_R3.ChipUtil1_16_R3.custom(ChipUtil1_16_R3.java:1206) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_16_R3.ChipUtil1_16_R3.toNMS(ChipUtil1_16_R3.java:365) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_16_R3.ChipUtil1_16_R3.removePathfinder(ChipUtil1_16_R3.java:389) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.ChipUtil.lambda$clearPathfinders$0(ChipUtil.java:54) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_372]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.ChipUtil.clearPathfinders(ChipUtil.java:54) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitAI.updateAI(BukkitAI.java:42) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitAI.clear(BukkitAI.java:164) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.clearPathfinders(Pet.java:138) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.initializeEntity(Pet.java:122) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.onEquip(Pet.java:87) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:105) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:157) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:66) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:31) ~[?:?]
        at be.isach.ultracosmetics.command.subcommands.SubCommandToggle.toggle(SubCommandToggle.java:92) ~[?:?]
        at be.isach.ultracosmetics.command.subcommands.SubCommandToggle.onExePlayer(SubCommandToggle.java:48) ~[?:?]
        at be.isach.ultracosmetics.command.CommandManager.onCommand(CommandManager.java:81) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-794]
        ... 19 more
```

**Comment by GamerCoder215** [comment]
PaperMC changed the pathfindergoal flag type for optimization reasons. More information is at PaperMC/Paper#9201. 

I'll try to fix this ASAP.
