### ISSUE TITLE
Casting issue with HOME memory

### ISSUE THREAD

**Issue by ShaneBeee** [GamerCoder215/MobChip#78]
### Bug Type

Console Errors

### MobChip Version

1.9.0

### Server Version

Paper 1.20.1

### Description

Im using this API in a Skript addon, and when trying to get the HOME memory of a villager, a casting error comes up saying an Optional cannot be cast to Location
Please ignore the Skript stuff
```vb
[14:45:41 ERROR]: #!#! Stack trace:
[14:45:41 ERROR]: #!#! java.lang.ClassCastException: Cannot cast java.util.Optional to org.bukkit.Location
[14:45:41 ERROR]: #!#!     at java.base/java.lang.Class.cast(Class.java:3991)
[14:45:41 ERROR]: #!#!     at SkMobChip-1.0-SNAPSHOT.jar//me.gamercoder215.mobchip.abstraction.v1_20_R1.ChipUtil1_20_R1.getMemory(ChipUtil1_20_R1.java:981)
[14:45:41 ERROR]: #!#!     at SkMobChip-1.0-SNAPSHOT.jar//me.gamercoder215.mobchip.bukkit.BukkitBrain.getMemory(BukkitBrain.java:291)
[14:45:41 ERROR]: #!#!     at SkMobChip-1.0-SNAPSHOT.jar//com.shanebeestudios.skmob.elements.expressions.ExprEntityMemory.get(ExprEntityMemory.java:57)
[14:45:41 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[14:45:41 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:123)
[14:45:41 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:108)
[14:45:41 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[14:45:41 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:45:41 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[14:45:41 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:290)
[14:45:41 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:220)
[14:45:41 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:217)
[14:45:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[14:45:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[14:45:41 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
[14:45:41 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[14:45:41 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[14:45:41 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[14:45:41 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[14:45:41 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Expected Behavior

no error :)

### Actual Behavior

Get error -> see description

**Comment by GamerCoder215** [comment]
Paper uses Optionals for Memory instead of the default object, most likely for optimization and API purposes. I may add support for it.
