### ISSUE TITLE
Broken CodeMC release

### ISSUE THREAD

**Issue by Blaackyy** [GamerCoder215/MobChip#91]
### Bug Type

Compatibility Issues, Other Unexpected Behavior

### MobChip Version

1.9.2

### Server Version

1.20.1

### Description

Hello, just wanted to go back and try a few things with MobChip, found out the release in codemc was not reobf. 

```java[17:25:18 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'th' in dev.blacky.treasurehunt.command.TreasureHuntCommand(treasurehunt)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1020) ~[purpur-1.20.1.jar:git-Purpur-2018]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2018]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2352) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2018]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2018]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2018]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2018]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2018]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2018]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2018]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2018]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/entity/LivingEntity
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at dev.blacky.treasurehunt.lib.mobchip.abstraction.ChipUtil.getWrapper(ChipUtil.java:188) ~[TreasureHunt-1.0.0.jar:?]
        at dev.blacky.treasurehunt.lib.mobchip.bukkit.BukkitBrain.<clinit>(BukkitBrain.java:45) ~[TreasureHunt-1.0.0.jar:?]
        at dev.blacky.treasurehunt.command.TreasureHuntCommand.execute(TreasureHuntCommand.kt:26) ~[TreasureHunt-1.0.0.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 22 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.entity.LivingEntity
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at dev.blacky.treasurehunt.lib.mobchip.abstraction.ChipUtil.getWrapper(ChipUtil.java:188) ~[TreasureHunt-1.0.0.jar:?]
        at dev.blacky.treasurehunt.lib.mobchip.bukkit.BukkitBrain.<clinit>(BukkitBrain.java:45) ~[TreasureHunt-1.0.0.jar:?]
        at dev.blacky.treasurehunt.command.TreasureHuntCommand.execute(TreasureHuntCommand.kt:26) ~[TreasureHunt-1.0.0.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 22 more
```

### Expected Behavior

N/A

### Actual Behavior

N/A

### Additional Information

Happened back at 1.9.0. Also reported it.

Best regards!

**Comment by GamerCoder215** [comment]
Just downloaded and decompiled the latest JAR and it appears to be obfuscated.

Are you downloading the `-dev` JAR? That one has mojang mappings.

**Comment by Blaackyy** [comment]
Found out gradle defaults to the dev classifier in all mobchip versions.
