### ISSUE TITLE
Error when clearing pathfinders from passive mobs on 1.17.1

### ISSUE THREAD

**Issue by datatags** [GamerCoder215/MobChip#92]
### Bug Type

Compatibility Issues, Console Errors

### MobChip Version

1.9.2-SNAPSHOT

### Server Version

This server is running CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1)

### Description

When trying to clear pathfinders from passive mobs, including cows, pigs, and sheep, an error is printed in console.

### Expected Behavior

Pathfinders should be cleared, and no error should occur

### Actual Behavior

This error is printed in console:
```
Caused by: java.lang.NullPointerException: Cannot read the array length because "array" is null
        at java.util.Arrays.stream(Arrays.java:5427) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_17_R1.ChipUtil1_17_R1.fromNMS(ChipUtil1_17_R1.java:1170) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_17_R1.ChipUtil1_17_R1.fromNMS(ChipUtil1_17_R1.java:1374) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_17_R1.ChipUtil1_17_R1.lambda$getGoals$0(ChipUtil1_17_R1.java:136) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_17_R1.ChipUtil1_17_R1.getGoals(ChipUtil1_17_R1.java:136) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitAI.updateMap(BukkitAI.java:36) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitAI.<init>(BukkitAI.java:31) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitBrain.getGoalAI(BukkitBrain.java:115) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.clearPathfinders(Pet.java:128) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.initializeEntity(Pet.java:112) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.onEquip(Pet.java:88) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:106) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:157) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:66) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:31) ~[?:?]
        at be.isach.ultracosmetics.menu.buttons.CosmeticButton.handleClick(CosmeticButton.java:119) ~[?:?]
        at be.isach.ultracosmetics.menu.buttons.CosmeticButton.onClick(CosmeticButton.java:79) ~[?:?]
        at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:182) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        ... 18 more
```

### Additional Information

1.16.5 and 1.18.2 don't seem to be affected, seems like it's just a 1.17.1 issue

**Comment by GamerCoder215** [comment]
Is this an issue in other versions or just 1.17.1? I would assume null errors would apply to more versions (most likely the older ones).

**Comment by datatags** [comment]
I tested 1.16.5, 1.17.1, 1.18.2, 1.20.1, and 1.20.2, but 1.17.1 was the only one with the issue

**Comment by GamerCoder215** [comment]
As it turns out, RecipeItemStack (known as Ingredient) required a `#buildChoices` method in order to be read properly. This method wasn't necessary anymore in 1.18, and I added it everywhere *except* 1.17 for some reason.
